# Generated by Django 6.0.5 on 2026-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción profesional completa', null=True),
        ),
    ]
